<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="23" passed="17" failed="3" skipped="3">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-01-08T14:54:01 BRT" name="Suite" finished-at="2025-01-08T14:54:22 BRT" duration-ms="21117">
    <groups>
    </groups>
    <test started-at="2025-01-08T14:54:01 BRT" name="AllTests" finished-at="2025-01-08T14:54:22 BRT" duration-ms="21117">
      <class name="base.LoginTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:base.LoginTest@6572421]" started-at="2025-01-08T14:54:01 BRT" name="setUp" finished-at="2025-01-08T14:54:10 BRT" duration-ms="8704" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testLogin()[pri:1, instance:base.LoginTest@6572421]" started-at="2025-01-08T14:54:10 BRT" name="testLogin" finished-at="2025-01-08T14:54:11 BRT" duration-ms="722" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:base.LoginTest@6572421]" started-at="2025-01-08T14:54:11 BRT" name="tearDown" finished-at="2025-01-08T14:54:11 BRT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- base.LoginTest -->
      <class name="ViewCare.SalesPointTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:ViewCare.SalesPointTest@5c5eefef]" started-at="2025-01-08T14:54:16 BRT" name="setUp" finished-at="2025-01-08T14:54:16 BRT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testOnlineEquipements()[pri:2, instance:ViewCare.SalesPointTest@5c5eefef]" started-at="2025-01-08T14:54:16 BRT" name="testOnlineEquipements" finished-at="2025-01-08T14:54:16 BRT" depends-on-methods="ViewCare.ViewCareTest.testViewCare" duration-ms="55" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Element 'totalMonitorados' is not visible expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Element 'totalMonitorados' is not visible expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at ViewCare.SalesPointTest.testOnlineEquipements(SalesPointTest.java:62)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testOnlineEquipements -->
        <test-method signature="testFoundClientSalesPoint()[pri:3, instance:ViewCare.SalesPointTest@5c5eefef]" started-at="2025-01-08T14:54:16 BRT" name="testFoundClientSalesPoint" finished-at="2025-01-08T14:54:17 BRT" depends-on-methods="ViewCare.ViewCareTest.testViewCare" duration-ms="535" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFoundClientSalesPoint -->
        <test-method signature="testFilterSalesPointByClient()[pri:3, instance:ViewCare.SalesPointTest@5c5eefef]" started-at="2025-01-08T14:54:17 BRT" name="testFilterSalesPointByClient" finished-at="2025-01-08T14:54:17 BRT" depends-on-methods="ViewCare.SalesPointTest.testFoundClientSalesPoint" duration-ms="321" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFilterSalesPointByClient -->
        <test-method signature="testFilterSalesPointByID()[pri:3, instance:ViewCare.SalesPointTest@5c5eefef]" started-at="2025-01-08T14:54:17 BRT" name="testFilterSalesPointByID" finished-at="2025-01-08T14:54:17 BRT" depends-on-methods="ViewCare.SalesPointTest.testFoundClientSalesPoint" duration-ms="330" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFilterSalesPointByID -->
        <test-method signature="testFilterSalesPointByLastMessage()[pri:3, instance:ViewCare.SalesPointTest@5c5eefef]" started-at="2025-01-08T14:54:17 BRT" name="testFilterSalesPointByLastMessage" finished-at="2025-01-08T14:54:18 BRT" depends-on-methods="ViewCare.SalesPointTest.testFoundClientSalesPoint" duration-ms="309" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFilterSalesPointByLastMessage -->
        <test-method signature="testFilterSalesPointByOnlineEquipment()[pri:3, instance:ViewCare.SalesPointTest@5c5eefef]" started-at="2025-01-08T14:54:18 BRT" name="testFilterSalesPointByOnlineEquipment" finished-at="2025-01-08T14:54:18 BRT" depends-on-methods="ViewCare.SalesPointTest.testFoundClientSalesPoint" duration-ms="328" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFilterSalesPointByOnlineEquipment -->
        <test-method signature="testFilterSalesPointBySalesPoint()[pri:3, instance:ViewCare.SalesPointTest@5c5eefef]" started-at="2025-01-08T14:54:18 BRT" name="testFilterSalesPointBySalesPoint" finished-at="2025-01-08T14:54:18 BRT" depends-on-methods="ViewCare.SalesPointTest.testFoundClientSalesPoint" duration-ms="334" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFilterSalesPointBySalesPoint -->
        <test-method signature="testFilterSalesPointByServiceOrder()[pri:3, instance:ViewCare.SalesPointTest@5c5eefef]" started-at="2025-01-08T14:54:18 BRT" name="testFilterSalesPointByServiceOrder" finished-at="2025-01-08T14:54:19 BRT" depends-on-methods="ViewCare.SalesPointTest.testFoundClientSalesPoint" duration-ms="307" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFilterSalesPointByServiceOrder -->
        <test-method signature="testFilterSalesPointByTotalEquipment()[pri:3, instance:ViewCare.SalesPointTest@5c5eefef]" started-at="2025-01-08T14:54:19 BRT" name="testFilterSalesPointByTotalEquipment" finished-at="2025-01-08T14:54:19 BRT" depends-on-methods="ViewCare.SalesPointTest.testFoundClientSalesPoint" duration-ms="321" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFilterSalesPointByTotalEquipment -->
        <test-method signature="testAssertNumberOfCLients()[pri:4, instance:ViewCare.SalesPointTest@5c5eefef]" started-at="2025-01-08T14:54:19 BRT" name="testAssertNumberOfCLients" finished-at="2025-01-08T14:54:19 BRT" depends-on-methods="ViewCare.SalesPointTest.testFoundClientSalesPoint" duration-ms="34" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Number of Shown Sales Points And Number of Sales Points Are Different expected [3] but found [4]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Number of Shown Sales Points And Number of Sales Points Are Different expected [3] but found [4]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at ViewCare.SalesPointTest.testAssertNumberOfCLients(SalesPointTest.java:166)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAssertNumberOfCLients -->
        <test-method signature="testAssertNumberOfShowedResults()[pri:4, instance:ViewCare.SalesPointTest@5c5eefef]" started-at="2025-01-08T14:54:19 BRT" name="testAssertNumberOfShowedResults" finished-at="2025-01-08T14:54:19 BRT" depends-on-methods="ViewCare.SalesPointTest.testFoundClientSalesPoint" duration-ms="28" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAssertNumberOfShowedResults -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ViewCare.SalesPointTest@5c5eefef]" started-at="2025-01-08T14:54:19 BRT" name="tearDown" finished-at="2025-01-08T14:54:19 BRT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- ViewCare.SalesPointTest -->
      <class name="ViewCare.ViewCareTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:ViewCare.ViewCareTest@6c64cb25]" started-at="2025-01-08T14:54:11 BRT" name="setUp" finished-at="2025-01-08T14:54:11 BRT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testViewCare()[pri:1, instance:ViewCare.ViewCareTest@6c64cb25]" started-at="2025-01-08T14:54:11 BRT" name="testViewCare" finished-at="2025-01-08T14:54:16 BRT" depends-on-methods="base.LoginTest.testLogin" duration-ms="5424" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testViewCare -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ViewCare.ViewCareTest@6c64cb25]" started-at="2025-01-08T14:54:16 BRT" name="tearDown" finished-at="2025-01-08T14:54:16 BRT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- ViewCare.ViewCareTest -->
      <class name="ViewCare.EnterSalesPoint">
        <test-method signature="testFetchListAndClickTheTestSalesPoint()[pri:1, instance:ViewCare.EnterSalesPoint@16293aa2]" started-at="2025-01-08T14:54:19 BRT" name="testFetchListAndClickTheTestSalesPoint" finished-at="2025-01-08T14:54:19 BRT" depends-on-methods="ViewCare.SalesPointTest.testFoundClientSalesPoint" duration-ms="273" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFetchListAndClickTheTestSalesPoint -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:ViewCare.EnterSalesPoint@16293aa2]" started-at="2025-01-08T14:54:19 BRT" name="setUp" finished-at="2025-01-08T14:54:19 BRT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testValidateNameSalesPoint()[pri:2, instance:ViewCare.EnterSalesPoint@16293aa2]" started-at="2025-01-08T14:54:19 BRT" name="testValidateNameSalesPoint" finished-at="2025-01-08T14:54:19 BRT" depends-on-methods="ViewCare.EnterSalesPoint.testFetchListAndClickTheTestSalesPoint" duration-ms="59" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testValidateNameSalesPoint -->
        <test-method signature="testValidatesNumberOfOS()[pri:2, instance:ViewCare.EnterSalesPoint@16293aa2]" started-at="2025-01-08T14:54:19 BRT" name="testValidatesNumberOfOS" finished-at="2025-01-08T14:54:19 BRT" depends-on-methods="ViewCare.EnterSalesPoint.testFetchListAndClickTheTestSalesPoint" duration-ms="18" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testValidatesNumberOfOS -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ViewCare.EnterSalesPoint@16293aa2]" started-at="2025-01-08T14:54:19 BRT" name="tearDown" finished-at="2025-01-08T14:54:19 BRT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- ViewCare.EnterSalesPoint -->
      <class name="ViewCare.EnterPGDM">
        <test-method is-config="true" signature="setUp()[pri:0, instance:ViewCare.EnterPGDM@595b007d]" started-at="2025-01-08T14:54:22 BRT" name="setUp" finished-at="2025-01-08T14:54:22 BRT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testLastInfoFirstMonitorableIsValidPGDM()[pri:1, instance:ViewCare.EnterPGDM@595b007d]" started-at="2025-01-08T14:54:22 BRT" name="testLastInfoFirstMonitorableIsValidPGDM" finished-at="2025-01-08T14:54:22 BRT" depends-on-methods="ViewCare.EnterSalesPoint.testFetchListAndClickTheTestSalesPoint" duration-ms="29" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The time difference is more than 6 minutes. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The time difference is more than 6 minutes. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at ViewCare.BaseEquipmentTest.validateLastInfo(BaseEquipmentTest.java:39)
at ViewCare.EnterPGDM.testLastInfoFirstMonitorableIsValidPGDM(EnterPGDM.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLastInfoFirstMonitorableIsValidPGDM -->
        <test-method signature="testAcessEquipmentPGDM()[pri:2, instance:ViewCare.EnterPGDM@595b007d]" started-at="2025-01-08T14:54:22 BRT" name="testAcessEquipmentPGDM" finished-at="2025-01-08T14:54:22 BRT" depends-on-methods="ViewCare.EnterPGDM.testLastInfoFirstMonitorableIsValidPGDM" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method EnterPGDM.testAcessEquipmentPGDM()[pri:2, instance:ViewCare.EnterPGDM@595b007d] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method EnterPGDM.testAcessEquipmentPGDM()[pri:2, instance:ViewCare.EnterPGDM@595b007d] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAcessEquipmentPGDM -->
        <test-method signature="testGoBackFromEquipmentPGDM()[pri:3, instance:ViewCare.EnterPGDM@595b007d]" started-at="2025-01-08T14:54:22 BRT" name="testGoBackFromEquipmentPGDM" finished-at="2025-01-08T14:54:22 BRT" depends-on-methods="ViewCare.EnterPGDM.testAcessEquipmentPGDM" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method EnterPGDM.testGoBackFromEquipmentPGDM()[pri:3, instance:ViewCare.EnterPGDM@595b007d] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method EnterPGDM.testGoBackFromEquipmentPGDM()[pri:3, instance:ViewCare.EnterPGDM@595b007d] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGoBackFromEquipmentPGDM -->
        <test-method signature="testGoBackFromSalesPoint()[pri:4, instance:ViewCare.EnterPGDM@595b007d]" started-at="2025-01-08T14:54:22 BRT" name="testGoBackFromSalesPoint" finished-at="2025-01-08T14:54:22 BRT" depends-on-methods="ViewCare.EnterPGDM.testGoBackFromEquipmentPGDM" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method EnterPGDM.testGoBackFromSalesPoint()[pri:4, instance:ViewCare.EnterPGDM@595b007d] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method EnterPGDM.testGoBackFromSalesPoint()[pri:4, instance:ViewCare.EnterPGDM@595b007d] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGoBackFromSalesPoint -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ViewCare.EnterPGDM@595b007d]" started-at="2025-01-08T14:54:22 BRT" name="tearDown" finished-at="2025-01-08T14:54:22 BRT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- ViewCare.EnterPGDM -->
      <class name="ViewCare.EnterController">
        <test-method is-config="true" signature="setUp()[pri:0, instance:ViewCare.EnterController@5158b42f]" started-at="2025-01-08T14:54:19 BRT" name="setUp" finished-at="2025-01-08T14:54:19 BRT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testLastInfoFirstMonitorableIsValidController()[pri:1, instance:ViewCare.EnterController@5158b42f]" started-at="2025-01-08T14:54:19 BRT" name="testLastInfoFirstMonitorableIsValidController" finished-at="2025-01-08T14:54:20 BRT" depends-on-methods="ViewCare.EnterSalesPoint.testFetchListAndClickTheTestSalesPoint" duration-ms="552" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLastInfoFirstMonitorableIsValidController -->
        <test-method signature="testAcessEquipmentController()[pri:2, instance:ViewCare.EnterController@5158b42f]" started-at="2025-01-08T14:54:20 BRT" name="testAcessEquipmentController" finished-at="2025-01-08T14:54:22 BRT" depends-on-methods="ViewCare.EnterController.testLastInfoFirstMonitorableIsValidController" duration-ms="2355" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAcessEquipmentController -->
        <test-method signature="testGoBackFromController()[pri:3, instance:ViewCare.EnterController@5158b42f]" started-at="2025-01-08T14:54:22 BRT" name="testGoBackFromController" finished-at="2025-01-08T14:54:22 BRT" duration-ms="10" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGoBackFromController -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ViewCare.EnterController@5158b42f]" started-at="2025-01-08T14:54:22 BRT" name="tearDown" finished-at="2025-01-08T14:54:22 BRT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- ViewCare.EnterController -->
    </test> <!-- AllTests -->
  </suite> <!-- Suite -->
</testng-results>
